@startuml
[*] --> Inativo

Inativo : Novo projeto criado, mas não ativado
Inativo --> Ativo : Ativar projeto
Inativo --> Excluido : Excluir projeto

Ativo : Projeto em andamento
Ativo --> Concluido : Concluir projeto
Ativo --> Excluido : Excluir projeto
Ativo --> Edicao : Editar projeto
Ativo --> EventoAdicionado : Adicionar evento

Edicao : Projeto sendo editado
Edicao --> Ativo : Salvar alterações

EventoAdicionado : Evento adicionado ao projeto
EventoAdicionado --> Ativo : Retornar ao estado ativo

Concluido : Projeto concluído
Concluido --> Ativo : Reativar projeto
Concluido --> Excluido : Excluir projeto

Excluido : Projeto excluído permanentemente

@enduml
